services:
  app:
    build: .
    command:
      /bin/sh -c "/usr/local/bin/wait-for-it.sh db:5432 -- python3 manage.py migrate --noinput && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./wait-for-it.sh:/usr/local/bin/wait-for-it.sh
      - ./:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always
    working_dir: /app/aimagestore

  db:
    container_name: postgres_aimagestore
    image: postgres:14.8
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: "aimagestore_db"
    expose:
      - "5432"
    ports:
      - "5432:5432"
    restart: always
