# fly.toml app configuration file generated for aimagestore on 2024-09-30T16:19:24+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'aimagestore'
primary_region = 'mad'
console_command = '/code/manage.py shell'

[build]

[deploy]
  release_command = 'python manage.py migrate --noinput'

[env]
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = "shared-cpu-1x"
  memory = "1024"

[[statics]]
  guest_path = '/code/staticfiles'
  url_prefix = '/static/'
